version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"
      day: "saturday"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
