// Generated by CoffeeScript 1.9.2
(function() {
  var chokidar, e, nwgui, nwwin, watcher,
    hasProp = {}.hasOwnProperty;

  window.CRASHED = false;

  if (typeof process !== "undefined" && process !== null) {
    nwgui = window.require("nw.gui");
    nwwin = nwgui.Window.get(window);
    process.removeAllListeners("uncaughtException");
    process.on("uncaughtException", function(e) {
      var ref;
      if (!window.CRASHED) {
        if (typeof console !== "undefined" && console !== null) {
          if (typeof console.warn === "function") {
            console.warn("CRASH");
          }
        }
      }
      window.CRASHED = true;
      if (!nwwin.isDevToolsOpen()) {
        nwwin.showDevTools();
      }
      if (((ref = nwgui.App.manifest.window) != null ? ref.show : void 0) === false) {
        return nwwin.show();
      }
    });
    window.addEventListener("keydown", function(e) {
      if (e.keyCode === 123) {
        if (nwwin.isDevToolsOpen()) {
          return nwwin.closeDevTools();
        } else {
          return nwwin.showDevTools();
        }
      }
    });
    try {
      chokidar = window.require("nw-dev/node_modules/chokidar/");
    } catch (_error) {
      e = _error;
      console.warn("Live reload disabled:", e.stack);
    }
    if (chokidar) {
      watcher = chokidar.watch(".", {
        ignored: /node_modules|npm-debug\.log|\.git|\.hg|\.svn/
      });
      watcher.on("change", function(path) {
        var fs, height, k, newwin, newwin_options, pkg, ref, ref1, ref2, v, width, x, y;
        watcher.close();
        ref = global.require.cache;
        for (k in ref) {
          if (!hasProp.call(ref, k)) continue;
          delete global.require.cache[k];
        }
        nwwin.removeAllListeners();
        nwwin.closeDevTools();
        if (path === "package.json") {
          fs = require("fs");
          pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
          Object.defineProperty(nwgui.App, "manifest", {
            value: pkg,
            configurable: true
          });
          x = nwwin.x, y = nwwin.y;
          width = window.innerWidth;
          height = window.innerHeight;
          window.close();
          newwin_options = {};
          ref1 = pkg.window;
          for (k in ref1) {
            v = ref1[k];
            newwin_options[k] = v;
          }
          ref2 = {
            x: x,
            y: y,
            width: width,
            height: height
          };
          for (k in ref2) {
            v = ref2[k];
            newwin_options[k] = v;
          }
          return newwin = nwgui.Window.open(window.location.href, newwin_options);
        } else {
          return typeof location !== "undefined" && location !== null ? location.reload() : void 0;
        }
      });
    }
  }

  window.onerror = function(e) {
    if (!window.CRASHED) {
      if (typeof console !== "undefined" && console !== null) {
        if (typeof console.warn === "function") {
          console.warn("CRASH");
        }
      }
    }
    window.CRASHED = true;
    return typeof console !== "undefined" && console !== null ? typeof console.error === "function" ? console.error("Got exception:", e) : void 0 : void 0;
  };

}).call(this);
